baseurl = "https://www.dylancraven.com"
languageCode = "en-us"
title = "Dylan Craven"
theme = "hugo-lithium"
style="green"

googleAnalytics = "UA-152694415-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:title"

[[menu.main]]
    name = "Home"
    url = "/about/"
    weight =1

[[menu.main]]
    name = "Research"
    url = "/research/"
    weight =2

[[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight =3
    
[[menu.main]]
    name = "Team"
    url = "/equipo/"
    weight =4
    
[[menu.main]]
    name = "Join!/Unete!"
    url = "/join/"
    weight =5    
[[menu.main]]
    name = "Data"
    url = "/data/"
    weight =6
        
    
#[[menu.main]]
#    name = "GitHub"
#   url = "https://github.com/dylancraven"
#  weight =6
#[[menu.main]]
#    name = "Twitter"
#    url = "https://twitter.com/DylanJCraven"
#    weight =7

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "trees.png"

    [params.logo]
    url = "https://www.dylan.craven.com"
    width = 100
    height = 100
    alt = "Logo"
