baseurl = "https://www.dylancraven.com"
languageCode = "en-us"
title = "Dylan Craven"
theme = "hugo-universal"

googleAnalytics = "UA-152694415-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


[[menu.main]]
    name = "Research"
    url = "/research/"
    weight =1

[[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight =2
    
[[menu.main]]
    name = "Team"
    url = "/equipo/"
    weight =3
    
[[menu.main]]
    name = "Join!/Unete!"
    url = "/join/"
    weight =4    
    
[[menu.main]]
    name = "Data"
    url = "/data/"
    weight =5
    
[params]
    #description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "logo.png"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Home"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
